/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useRef, useEffect } from 'react';
import { 
  Send, 
  BookOpen, 
  ChevronRight, 
  Download, 
  Loader2, 
  MessageSquare, 
  Settings, 
  Terminal,
  Layers,
  Database,
  Globe,
  Layout as LayoutIcon,
  Zap,
  CheckCircle2,
  Circle
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { chatWithAI } from './services/aiService';
import { SDD, INITIAL_SDD, Message, SectionId, SpecSection } from './types';

export default function App() {
  const [sdd, setSdd] = useState<SDD>(INITIAL_SDD);
  const [activeSectionId, setActiveSectionId] = useState<SectionId>('vision');
  const [messages, setMessages] = useState<Message[]>([
    { role: 'model', content: '¡Hola! Soy tu Arquitecto de SDD. Cuéntame sobre la aplicación que quieres crear y te ayudaré a definir todos sus requisitos y especificaciones técnicas.' }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSendMessage = async () => {
    if (!input.trim() || isLoading) return;

    const userMessage: Message = { role: 'user', content: input };
    const newMessages = [...messages, userMessage];
    setMessages(newMessages);
    setInput('');
    setIsLoading(true);

    try {
      const response = await chatWithAI(newMessages);
      
      let nextMessages = [...newMessages];

      // Handle function calls
      if (response.functionCalls) {
        for (const call of response.functionCalls) {
          if (call.name === 'update_spec_section') {
            const { sectionId, content, status } = call.args as any;
            setSdd(prev => ({
              ...prev,
              sections: {
                ...prev.sections,
                [sectionId]: {
                  ...prev.sections[sectionId as SectionId],
                  content,
                  status
                }
              },
              lastUpdated: Date.now()
            }));
            setActiveSectionId(sectionId as SectionId);
          } else if (call.name === 'update_project_name') {
            const { name } = call.args as any;
            setSdd(prev => ({ ...prev, projectName: name }));
          }
        }
      }

      if (response.text) {
        nextMessages.push({ role: 'model', content: response.text });
      } else {
        nextMessages.push({ role: 'model', content: 'He actualizado las especificaciones basándome en lo que hemos hablado. ¿Qué más te gustaría definir?' });
      }

      setMessages(nextMessages);
    } catch (error) {
      console.error(error);
      setMessages(prev => [...prev, { role: 'model', content: 'Lo siento, ha ocurrido un error al procesar tu solicitud. Por favor, asegúrate de que la clave de API esté configurada.' }]);
    } finally {
      setIsLoading(false);
    }
  };

  const getSectionIcon = (id: SectionId) => {
    switch (id) {
      case 'vision': return <Zap className="w-4 h-4" />;
      case 'requirements': return <BookOpen className="w-4 h-4" />;
      case 'tech_stack': return <Terminal className="w-4 h-4" />;
      case 'data_model': return <Database className="w-4 h-4" />;
      case 'endpoints': return <Globe className="w-4 h-4" />;
      case 'ux_flow': return <ChevronRight className="w-4 h-4" />;
      case 'components': return <Layers className="w-4 h-4" />;
      default: return <LayoutIcon className="w-4 h-4" />;
    }
  };

  const downloadSDD = () => {
    let fullText = `# Software Design Document (SDD) - Generated by SDD Genesis\n\n`;
    Object.values(sdd.sections).forEach(section => {
      fullText += `## ${section.title}\n\n${section.content || '_Sin contenido aún_'}\n\n---\n\n`;
    });
    
    const blob = new Blob([fullText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `spec_driven_development_${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex h-screen bg-[#050505] text-slate-300 font-sans overflow-hidden">
      {/* Sidebar */}
      <aside className="w-72 border-r border-white/5 bg-[#080808] flex flex-col overflow-hidden">
        <div className="p-6 border-b border-white/5 bg-[#0A0A0A]">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-8 h-8 rounded bg-indigo-600 flex items-center justify-center text-white font-bold">S</div>
            <h1 className="text-lg font-medium text-white tracking-tight">SDD Genesis <span className="text-slate-500 font-normal ml-1 text-xs">v1.0</span></h1>
          </div>
          
          <div className="px-3 py-2 bg-white/5 rounded border border-white/10">
            <p className="text-[10px] uppercase font-bold text-slate-500 tracking-wider mb-1">Active Project</p>
            <p className="text-sm font-medium text-white truncate italic">{sdd.projectName}</p>
          </div>
        </div>

        <nav className="flex-1 overflow-y-auto p-4 space-y-1 custom-scrollbar">
          <div className="px-3 py-2 text-[10px] font-bold text-slate-600 uppercase tracking-widest">Document Sections</div>
          {Object.values(sdd.sections).map((section) => (
            <button
              key={section.id}
              id={`nav-${section.id}`}
              onClick={() => setActiveSectionId(section.id)}
              className={`w-full flex items-center gap-3 px-3 py-2.5 rounded text-sm transition-all group ${
                activeSectionId === section.id 
                  ? 'bg-white/5 border border-white/10 text-indigo-400' 
                  : 'text-slate-400 hover:text-white hover:bg-white/5'
              }`}
            >
              <span className={`${activeSectionId === section.id ? 'text-indigo-400' : 'text-slate-500 group-hover:text-slate-300'}`}>
                {getSectionIcon(section.id)}
              </span>
              <span className="flex-1 text-left">{section.title}</span>
              {section.status === 'complete' ? (
                <CheckCircle2 className="w-3.5 h-3.5 text-green-500/70" />
              ) : section.status === 'draft' ? (
                <div className="w-1.5 h-1.5 rounded-full bg-indigo-500 shadow-[0_0_8px_rgba(99,102,241,0.5)]" />
              ) : (
                <div className="w-1.5 h-1.5 rounded-full border border-white/20" />
              )}
            </button>
          ))}
        </nav>

        <div className="p-4 border-t border-white/5">
          <button 
            id="export-btn"
            onClick={downloadSDD}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-white text-black rounded text-xs font-bold hover:bg-slate-200 transition-colors uppercase tracking-wider"
          >
            <Download className="w-4 h-4" />
            Export SDD Bundle
          </button>
        </div>
      </aside>

      {/* Main Content Split */}
      <main className="flex-1 flex overflow-hidden">
        
        {/* Chat Pane */}
        <section className="w-1/2 flex flex-col border-r border-white/5 bg-[#050505]">
          <header className="px-6 py-4 border-b border-white/5 flex items-center justify-between bg-[#0A0A0A]">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-full bg-slate-800 flex items-center justify-center border border-white/10">
                <MessageSquare className="w-4 h-4 text-indigo-400" />
              </div>
              <div>
                <h2 className="text-xs font-bold text-white uppercase tracking-wider">Architect Dialogue</h2>
                <div className="flex items-center gap-1.5 text-[10px] text-slate-500">
                  <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 animate-pulse"></span>
                  LMM-Powered Analytics Active
                </div>
              </div>
            </div>
          </header>

          <div 
            ref={scrollRef}
            className="flex-1 overflow-y-auto p-8 space-y-8 custom-scrollbar"
          >
            <AnimatePresence initial={false}>
              {messages.map((m, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className={`flex gap-4 ${m.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}
                >
                  <div className={`w-8 h-8 rounded-full flex-shrink-0 flex items-center justify-center border ${
                    m.role === 'user' 
                      ? 'bg-indigo-600 border-indigo-500 text-white' 
                      : 'bg-slate-800 border-white/10 text-indigo-400'
                  }`}>
                    {m.role === 'user' ? <span className="text-[10px] font-bold">ME</span> : <Zap className="w-4 h-4" />}
                  </div>

                  <div className={`max-w-[85%] ${
                    m.role === 'user' 
                      ? 'bg-white/5 px-4 py-3 rounded-2xl rounded-tr-none border border-white/5 text-slate-200' 
                      : 'text-white font-light text-lg leading-relaxed'
                  }`}>
                    {m.content}
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>
            {isLoading && (
              <div className="flex items-center gap-4">
                <div className="w-8 h-8 rounded-full bg-slate-800 flex items-center justify-center border border-white/10">
                  <Loader2 className="w-4 h-4 text-indigo-400 animate-spin" />
                </div>
                <div className="text-slate-500 italic text-sm animate-pulse">Analizando parámetros técnicos...</div>
              </div>
            )}
          </div>

          <div className="p-4 border-t border-white/5 bg-[#0A0A0A]">
            <div className="relative group">
              <textarea
                id="message-input"
                rows={1}
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    handleSendMessage();
                  }
                }}
                placeholder="Describe a feature or answer the AI..."
                className="w-full bg-white/5 border border-white/10 rounded-xl px-6 py-4 focus:outline-none focus:border-indigo-500/50 text-sm placeholder:text-slate-600 text-white transition-all resize-none"
              />
              <div className="absolute right-4 top-4 flex items-center gap-2 pointer-events-none">
                <span className="text-[9px] text-slate-600 font-mono uppercase tracking-widest hidden md:block">Cmd + Enter / Send</span>
                <button
                  id="send-btn"
                  onClick={handleSendMessage}
                  disabled={!input.trim() || isLoading}
                  className="p-1.5 bg-indigo-600 text-white rounded pointer-events-auto disabled:opacity-30 disabled:grayscale transition-all hover:scale-105"
                >
                  <Send className="w-3 h-3" />
                </button>
              </div>
            </div>
          </div>
        </section>

        {/* Preview Pane */}
        <section className="w-1/2 flex flex-col bg-[#080808]">
          <header className="px-8 py-5 border-b border-white/5 flex items-center justify-between bg-[#0A0A0A]">
            <div className="flex items-center gap-4">
              <div className="flex flex-col">
                <span className="text-[10px] font-semibold text-slate-500 uppercase tracking-widest mb-0.5">Live Artifact Preview</span>
                <h2 className="text-lg font-medium text-white tracking-tight">{sdd.sections[activeSectionId].title}</h2>
              </div>
            </div>
            <div className="flex items-center gap-2 px-3 py-1 bg-green-500/10 border border-green-500/20 rounded-full">
              <div className="w-1.5 h-1.5 rounded-full bg-green-400" />
              <span className="text-[10px] font-bold text-green-400 uppercase">Valid</span>
            </div>
          </header>

          <div className="flex-1 overflow-y-auto p-12 markdown-container custom-scrollbar relative">
            {sdd.sections[activeSectionId].content ? (
              <motion.div
                key={activeSectionId}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                className="max-w-none"
              >
                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                  {sdd.sections[activeSectionId].content}
                </ReactMarkdown>
              </motion.div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-center space-y-6 opacity-20 transition-opacity hover:opacity-40">
                <div className="p-10 rounded-full border border-dashed border-slate-500">
                  {getSectionIcon(activeSectionId)}
                </div>
                <div className="space-y-2">
                  <h3 className="text-white font-medium uppercase tracking-widest text-sm">Waiting for generation</h3>
                  <p className="text-xs text-slate-400 max-w-[280px] mx-auto leading-relaxed italic">Talk to the architect to materialize this section of your specification.</p>
                </div>
              </div>
            )}
            
            {/* Context Awareness overlay */}
            <div className="absolute top-4 right-4 z-10 opacity-30 pointer-events-none">
              <div className="px-2 py-1 bg-black border border-white/5 rounded text-[10px] font-mono text-indigo-400">
                SEC_ID: {activeSectionId.toUpperCase()}
              </div>
            </div>
          </div>

          <div className="p-6 border-t border-white/5 bg-[#0A0A0A]">
            <div className="flex flex-col space-y-4">
              <div className="flex justify-between items-end">
                <div className="flex flex-col">
                  <span className="text-[10px] uppercase font-bold tracking-widest text-slate-500">Spec Complexity Mapping</span>
                  <div className="text-xs text-white font-mono mt-1">
                    System Readiness: <span className="text-indigo-400">High</span>
                  </div>
                </div>
                <div className="text-right">
                  <span className="text-[10px] uppercase font-bold tracking-widest text-slate-500">Entropy Balance</span>
                  <div className="text-[11px] font-mono text-slate-400">STABLE</div>
                </div>
              </div>
              <div className="w-full h-1 bg-slate-900 overflow-hidden rounded-full">
                <motion.div 
                  initial={{ width: 0 }}
                  animate={{ width: `${(Object.values(sdd.sections).filter(s => s.status !== 'empty').length / 7) * 100}%` }}
                  className="h-full bg-indigo-600 shadow-[0_0_12px_rgba(79,70,229,0.5)]" 
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
